using System;
using OverloadedOperators;

Point p1 = new(100, 100);
Point p2 = new(40, 40);
Console.WriteLine(p1);
Console.WriteLine(p2);
Console.WriteLine();
Point p3 = p1 + p2;
Point p4 = p1 - p2;
Console.WriteLine(p3);
Console.WriteLine(p4);
Console.WriteLine(p3 == p4);
p3 = p3 - 40;
p4 = p4 + 40;
Console.WriteLine(p3);
Console.WriteLine(p4);
Console.WriteLine(p3 == p4);
p3 += 50;
p4 -= 50;
Console.WriteLine(p3);
Console.WriteLine(p4);
p3++;
p4--;
Console.WriteLine(p3);
Console.WriteLine(p4);
++p3;
--p4;
Console.WriteLine(p3);
Console.WriteLine(p4);
Console.WriteLine(p3 == p4);
Console.WriteLine(p3 != p4);